### ISSUE TITLE
docker这样不对吗？为什么还是上传失败

### ISSUE THREAD

**Issue by cyclestudy** [Yohann0617/tgNetDisc#7]
<img width="695" alt="image" src="https://github.com/user-attachments/assets/cac853dc-c635-4200-8338-cd1b2e5e6e0f">
<img width="441" alt="image" src="https://github.com/user-attachments/assets/d0bfba1f-358b-4b71-bc92-2aa29ffb4a67">
<img width="892" alt="image" src="https://github.com/user-attachments/assets/5904db1b-9c74-42d7-90c0-ed146bb77137">

**Comment by Yohann0617** [comment]
看看docker日志

**Comment by cyclestudy** [comment]
> 看看docker日志
<img width="417" alt="image" src="https://github.com/user-attachments/assets/b8315692-b230-42a1-8405-738b0b77a4f1">

网页上传了一张（失败

还是没有日志输出

**Comment by Yohann0617** [comment]
> > 看看docker日志
> 
> <img alt="image" width="417" src="https://private-user-images.githubusercontent.com/115349959/350859865-b8315692-b230-42a1-8405-738b0b77a4f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzA0NDAsIm5iZiI6MTcyMTYzMDE0MCwicGF0aCI6Ii8xMTUzNDk5NTkvMzUwODU5ODY1LWI4MzE1NjkyLWIyMzAtNDJhMS04NDA1LTczOGIwYjc3YTRmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwNjM1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjBhZjc0YWQ1MDFmNzRiM2IwNTAyZGM2NDVlODlmYzJmMDQzZGYwYjMxZmJhYmM2NDMwMmFlZTEwZTA5MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jdyMoSwqivpZ0HnUgEwXXKk4h8ekfyhvE1ek0eawgTE">
> 网页上传了一张（失败
> 
> 还是没有日志输出

国内VPS？

**Comment by cyclestudy** [comment]
> > > 看看docker日志
> > 
> > 
> > <img alt="image" width="417" src="https://private-user-images.githubusercontent.com/115349959/350859865-b8315692-b230-42a1-8405-738b0b77a4f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzA0NDAsIm5iZiI6MTcyMTYzMDE0MCwicGF0aCI6Ii8xMTUzNDk5NTkvMzUwODU5ODY1LWI4MzE1NjkyLWIyMzAtNDJhMS04NDA1LTczOGIwYjc3YTRmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwNjM1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjBhZjc0YWQ1MDFmNzRiM2IwNTAyZGM2NDVlODlmYzJmMDQzZGYwYjMxZmJhYmM2NDMwMmFlZTEwZTA5MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jdyMoSwqivpZ0HnUgEwXXKk4h8ekfyhvE1ek0eawgTE">
> > 网页上传了一张（失败
> > 还是没有日志输出
> 
> 国内VPS？

TW

**Comment by Yohann0617** [comment]
> > > > 看看docker日志
> > > 
> > > 
> > > <img alt="image" width="417" src="https://private-user-images.githubusercontent.com/115349959/350859865-b8315692-b230-42a1-8405-738b0b77a4f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzA0NDAsIm5iZiI6MTcyMTYzMDE0MCwicGF0aCI6Ii8xMTUzNDk5NTkvMzUwODU5ODY1LWI4MzE1NjkyLWIyMzAtNDJhMS04NDA1LTczOGIwYjc3YTRmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwNjM1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjBhZjc0YWQ1MDFmNzRiM2IwNTAyZGM2NDVlODlmYzJmMDQzZGYwYjMxZmJhYmM2NDMwMmFlZTEwZTA5MWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jdyMoSwqivpZ0HnUgEwXXKk4h8ekfyhvE1ek0eawgTE">
> > > 网页上传了一张（失败
> > > 还是没有日志输出
> > 
> > 
> > 国内VPS？
> 
> TW

ping google.com能ping通的话，再看看你端口有没有放行，域名解析正不正确

**Comment by cyclestudy** [comment]
PING google.com (142.251.42.238) 56(84) bytes of data.
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=1 ttl=111 time=1.18 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=2 ttl=111 time=0.914 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=3 ttl=111 time=0.897 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=4 ttl=111 time=1.00 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=5 ttl=111 time=0.861 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=6 ttl=111 time=0.924 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=7 ttl=111 time=0.988 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=8 ttl=111 time=0.942 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=9 ttl=111 time=0.852 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=10 ttl=111 time=0.931 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=11 ttl=111 time=0.904 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=12 ttl=111 time=0.913 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=13 ttl=111 time=0.912 ms
64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=14 ttl=111 time=0.890 ms

是不是有点问题？
PING pornhub.com (66.254.114.41) 56(84) bytes of data.
64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=1 ttl=44 time=33.5 ms
64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=2 ttl=44 time=32.1 ms
64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=3 ttl=44 time=32.3 ms
64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=4 ttl=44 time=32.3 ms
64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=5 ttl=44 time=32.2 ms
64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=6 ttl=44 time=32.2 ms
64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=7 ttl=44 time=32.1 ms
端口都放行了 反代也成功的

**Comment by Yohann0617** [comment]
> PING google.com (142.251.42.238) 56(84) bytes of data. 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=1 ttl=111 time=1.18 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=2 ttl=111 time=0.914 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=3 ttl=111 time=0.897 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=4 ttl=111 time=1.00 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=5 ttl=111 time=0.861 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=6 ttl=111 time=0.924 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=7 ttl=111 time=0.988 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=8 ttl=111 time=0.942 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=9 ttl=111 time=0.852 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=10 ttl=111 time=0.931 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=11 ttl=111 time=0.904 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=12 ttl=111 time=0.913 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=13 ttl=111 time=0.912 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=14 ttl=111 time=0.890 ms
> 
> 是不是有点问题？ PING pornhub.com (66.254.114.41) 56(84) bytes of data. 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=1 ttl=44 time=33.5 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=2 ttl=44 time=32.1 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=3 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=4 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=5 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=6 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=7 ttl=44 time=32.1 ms 端口都放行了 反代也成功的

你可以试试原作者的，如果也不行那就是你的问题了

**Comment by cyclestudy** [comment]
> > PING google.com (142.251.42.238) 56(84) bytes of data. 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=1 ttl=111 time=1.18 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=2 ttl=111 time=0.914 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=3 ttl=111 time=0.897 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=4 ttl=111 time=1.00 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=5 ttl=111 time=0.861 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=6 ttl=111 time=0.924 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=7 ttl=111 time=0.988 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=8 ttl=111 time=0.942 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=9 ttl=111 time=0.852 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=10 ttl=111 time=0.931 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=11 ttl=111 time=0.904 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=12 ttl=111 time=0.913 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=13 ttl=111 time=0.912 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=14 ttl=111 time=0.890 ms
> > 是不是有点问题？ PING pornhub.com (66.254.114.41) 56(84) bytes of data. 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=1 ttl=44 time=33.5 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=2 ttl=44 time=32.1 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=3 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=4 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=5 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=6 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=7 ttl=44 time=32.1 ms 端口都放行了 反代也成功的
> 
> 你可以试试原作者的，如果也不行那就是你的问题了

<img width="1117" alt="image" src="https://github.com/user-attachments/assets/68f1fb3f-d07d-468f-b735-404162754c40">
比原作者优化了什么？

**Comment by Yohann0617** [comment]
> > > PING google.com (142.251.42.238) 56(84) bytes of data. 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=1 ttl=111 time=1.18 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=2 ttl=111 time=0.914 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=3 ttl=111 time=0.897 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=4 ttl=111 time=1.00 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=5 ttl=111 time=0.861 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=6 ttl=111 time=0.924 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=7 ttl=111 time=0.988 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=8 ttl=111 time=0.942 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=9 ttl=111 time=0.852 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=10 ttl=111 time=0.931 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=11 ttl=111 time=0.904 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=12 ttl=111 time=0.913 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=13 ttl=111 time=0.912 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=14 ttl=111 time=0.890 ms
> > > 是不是有点问题？ PING pornhub.com (66.254.114.41) 56(84) bytes of data. 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=1 ttl=44 time=33.5 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=2 ttl=44 time=32.1 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=3 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=4 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=5 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=6 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=7 ttl=44 time=32.1 ms 端口都放行了 反代也成功的
> > 
> > 
> > 你可以试试原作者的，如果也不行那就是你的问题了
> 
> <img alt="image" width="1117" src="https://private-user-images.githubusercontent.com/115349959/350870066-68f1fb3f-d07d-468f-b735-404162754c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzI2ODQsIm5iZiI6MTcyMTYzMjM4NCwicGF0aCI6Ii8xMTUzNDk5NTkvMzUwODcwMDY2LTY4ZjFmYjNmLWQwN2QtNDY4Zi1iNzM1LTQwNDE2Mjc1NGM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwNzEzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjczZmIyYjQ2ZjU4NGYzY2UxMTBhZGNkMGE2YWY3YmRiNzdkOThmNDYwMWE1OWZmM2RiY2YxM2YxNzk1Y2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sdDwYWEjVsO_QbXXpiJzyf3dB_zUD3LdRy147k4LnCA"> 比原作者优化了什么？

优化的地方基本都被原作者加上了

**Comment by cyclestudy** [comment]
> > > > PING google.com (142.251.42.238) 56(84) bytes of data. 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=1 ttl=111 time=1.18 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=2 ttl=111 time=0.914 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=3 ttl=111 time=0.897 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=4 ttl=111 time=1.00 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=5 ttl=111 time=0.861 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=6 ttl=111 time=0.924 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=7 ttl=111 time=0.988 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=8 ttl=111 time=0.942 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=9 ttl=111 time=0.852 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=10 ttl=111 time=0.931 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=11 ttl=111 time=0.904 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=12 ttl=111 time=0.913 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=13 ttl=111 time=0.912 ms 64 bytes from tsa01s11-in-f14.1e100.net (142.251.42.238): icmp_seq=14 ttl=111 time=0.890 ms
> > > > 是不是有点问题？ PING pornhub.com (66.254.114.41) 56(84) bytes of data. 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=1 ttl=44 time=33.5 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=2 ttl=44 time=32.1 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=3 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=4 ttl=44 time=32.3 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=5 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=6 ttl=44 time=32.2 ms 64 bytes from reflectededge.reflected.net (66.254.114.41): icmp_seq=7 ttl=44 time=32.1 ms 端口都放行了 反代也成功的
> > > 
> > > 
> > > 你可以试试原作者的，如果也不行那就是你的问题了
> > 
> > 
> > <img alt="image" width="1117" src="https://private-user-images.githubusercontent.com/115349959/350870066-68f1fb3f-d07d-468f-b735-404162754c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzI2ODQsIm5iZiI6MTcyMTYzMjM4NCwicGF0aCI6Ii8xMTUzNDk5NTkvMzUwODcwMDY2LTY4ZjFmYjNmLWQwN2QtNDY4Zi1iNzM1LTQwNDE2Mjc1NGM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwNzEzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjczZmIyYjQ2ZjU4NGYzY2UxMTBhZGNkMGE2YWY3YmRiNzdkOThmNDYwMWE1OWZmM2RiY2YxM2YxNzk1Y2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sdDwYWEjVsO_QbXXpiJzyf3dB_zUD3LdRy147k4LnCA"> 比原作者优化了什么？
> 
> 优化的地方基本都被原作者加上了

行吧，原作者的正常用
